# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# linux builds should be able to use the docker set up, but have been
# segfaulting on connection with either MariaDB or RPostgres
before_install:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then sudo /etc/init.d/postgresql stop || true; sh postgres-docker.sh; fi
  - if [ $TRAVIS_OS_NAME = "osx" ]; then sh postgres-travis-macos.sh; fi
  - if [ $TRAVIS_OS_NAME = "osx" ]; then sh mariadb-travis-macos.sh; fi

before_script:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then export DBTEST_DISABLE_PG=true; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then export DBTEST_DISABLE_MARIA=true; fi
  # we have to install from source, or else we get `result_fetch(res@ptr, n = n)`
  - R -q -e 'install.packages("RMariaDB", type = "source");'

r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx
matrix:
  exclude:
  - os: osx
    r: oldrel
  - os: osx
    r: devel


# clean up databases so they are not cached between runs
before_cache:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then docker exec -it dbtest-postgres psql -U travis -c "DROP DATABASE nycflights;"; fi
  - if [ $TRAVIS_OS_NAME = "osx" ]; then dropdb nycflights; fi
  - if [ $TRAVIS_OS_NAME = "osx" ]; then sudo mysql -u root -e "DROP DATABASE nycflights;"; fi


after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && test $TRAVIS_OS_NAME = "linux" && Rscript -e 'covr::codecov()'
