comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

coverage:
  ignore:
    - "R/use-dittodb.R"  # this internal function is called just for testing
